---
kind: pipeline
type: docker
name: 🚀 VIRIDA CI/CD Pipeline

# ========================================
# CONFIGURATION GLOBALE
# ========================================
platform:
  os: linux
  arch: amd64

# Variables d'environnement globales
environment:
  NODE_VERSION: "18"
  PYTHON_VERSION: "3.11"
  GO_VERSION: "1.21"
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

# Déclencheurs
trigger:
  branch:
    - main
    - staging
    - develop
  event:
    - push
    - pull_request
    - tag

# ========================================
# ÉTAPE 1: VALIDATION ET TESTS
# ========================================
steps:
  - name: 📥 Checkout Code
    image: alpine/git:latest
    commands:
      - git clone $DRONE_GIT_HTTP_URL .
      - git checkout $DRONE_COMMIT_SHA

  - name: 🔍 Code Quality Analysis
    image: sonarqube/sonar-scanner-cli:latest
    commands:
      - echo "🔍 Running code quality analysis..."
      - sonar-scanner
        -Dsonar.projectKey=virida
        -Dsonar.host.url=$SONAR_HOST_URL
        -Dsonar.login=$SONAR_TOKEN
        -Dsonar.branch.name=$DRONE_BRANCH
    when:
      event: [push, pull_request]

  - name: 🧪 Frontend Tests
    image: node:18-alpine
    commands:
      - cd apps/frontend-3d
      - npm ci --cache .npm
      - npm run test:ci
      - npm run lint
      - npm run build
    when:
      event: [push, pull_request]

  - name: 🧪 AI/ML Tests
    image: python:3.11-alpine
    commands:
      - cd apps/ai-ml
      - pip install -r requirements.txt
      - python -m pytest tests/ -v --cov=app --cov-report=xml
      - python -m flake8 app/
      - python -m black --check app/
    when:
      event: [push, pull_request]

  # Note: Gitea/Drone tests disabled - Gitea environment not working
  # Only Gitea database is available on Clever Cloud

  - name: 🔒 Security Scan
    image: securecodewarrior/docker-security-scan:latest
    commands:
      - echo "🔒 Running security scan..."
      - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock
        -v $(pwd):/workspace
        securecodewarrior/docker-security-scan:latest
        /workspace
    when:
      event: [push, pull_request]

# ========================================
# ÉTAPE 2: BUILD ET PACKAGING
# ========================================
  - name: 🏗️ Build Frontend
    image: node:18-alpine
    commands:
      - cd apps/frontend-3d
      - npm ci --cache .npm
      - npm run build:production
      - tar -czf frontend-3d.tar.gz dist/
    when:
      event: [push, tag]
      branch: [main, staging]

  - name: 🏗️ Build AI/ML
    image: python:3.11-alpine
    commands:
      - cd apps/ai-ml
      - pip install -r requirements.txt
      - python -m pip install --upgrade pip
      - pip install gunicorn
      - tar -czf ai-ml.tar.gz app/ requirements.txt wsgi.py
    when:
      event: [push, tag]
      branch: [main, staging]

  # Note: Gitea/Drone build disabled - Gitea environment not working
  # Only Gitea database is available on Clever Cloud

# ========================================
# ÉTAPE 3: DÉPLOIEMENT STAGING
# ========================================
  - name: 🚀 Deploy to Staging
    image: alpine:latest
    commands:
      - apk add --no-cache curl
      - echo "🚀 Deploying to staging environment..."
      
      # Déployer Frontend 3D
      - cd apps/frontend-3d
      - curl -X POST "$CLEVER_DEPLOY_URL/frontend-3d" \
          -H "Authorization: Bearer $CLEVER_TOKEN" \
          -F "archive=@frontend-3d.tar.gz"
      
      # Déployer AI/ML
      - cd ../ai-ml
      - curl -X POST "$CLEVER_DEPLOY_URL/ai-ml" \
          -H "Authorization: Bearer $CLEVER_TOKEN" \
          -F "archive=@ai-ml.tar.gz"
      
      # Note: Gitea/Drone deployment disabled - Gitea environment not working
      # Only Gitea database is available on Clever Cloud
    when:
      event: push
      branch: staging

# ========================================
# ÉTAPE 4: TESTS D'INTÉGRATION STAGING
# ========================================
  - name: 🧪 Integration Tests Staging
    image: curlimages/curl:latest
    commands:
      - echo "🧪 Running integration tests on staging..."
      
      # Attendre que les services soient prêts
      - sleep 60
      
      # Test Frontend 3D
      - curl -f https://virida-frontend-3d-staging.cleverapps.io/health || exit 1
      - echo "✅ Frontend 3D staging health check passed"
      
      # Test AI/ML
      - curl -f https://virida-ai-ml-staging.cleverapps.io/health || exit 1
      - echo "✅ AI/ML staging health check passed"
      
      # Note: Gitea/Drone health check disabled - Gitea environment not working
      # Only Gitea database is available on Clever Cloud
      
      # Tests de performance
      - response_time=$(curl -o /dev/null -s -w '%{time_total}' https://virida-frontend-3d-staging.cleverapps.io/)
      - echo "Frontend response time: ${response_time}s"
      - if [ $(echo "$response_time > 3.0" | bc -l) -eq 1 ]; then echo "⚠️ Warning: High response time"; fi
    when:
      event: push
      branch: staging

# ========================================
# ÉTAPE 5: DÉPLOIEMENT PRODUCTION
# ========================================
  - name: 🚀 Deploy to Production
    image: alpine:latest
    commands:
      - apk add --no-cache curl
      - echo "🚀 Deploying to production environment..."
      
      # Déployer Frontend 3D
      - cd apps/frontend-3d
      - curl -X POST "$CLEVER_DEPLOY_URL/frontend-3d-prod" \
          -H "Authorization: Bearer $CLEVER_TOKEN" \
          -F "archive=@frontend-3d.tar.gz"
      
      # Déployer AI/ML
      - cd ../ai-ml
      - curl -X POST "$CLEVER_DEPLOY_URL/ai-ml-prod" \
          -H "Authorization: Bearer $CLEVER_TOKEN" \
          -F "archive=@ai-ml.tar.gz"
      
      # Note: Gitea/Drone deployment disabled - Gitea environment not working
      # Only Gitea database is available on Clever Cloud
    when:
      event: push
      branch: main

# ========================================
# ÉTAPE 6: TESTS D'INTÉGRATION PRODUCTION
# ========================================
  - name: 🧪 Integration Tests Production
    image: curlimages/curl:latest
    commands:
      - echo "🧪 Running integration tests on production..."
      
      # Attendre que les services soient prêts
      - sleep 90
      
      # Test Frontend 3D
      - curl -f https://virida-frontend-3d.cleverapps.io/health || exit 1
      - echo "✅ Frontend 3D production health check passed"
      
      # Test AI/ML
      - curl -f https://virida-ai-ml.cleverapps.io/health || exit 1
      - echo "✅ AI/ML production health check passed"
      
      # Note: Gitea/Drone health check disabled - Gitea environment not working
      # Only Gitea database is available on Clever Cloud
      
      # Tests de performance avancés
      - response_time=$(curl -o /dev/null -s -w '%{time_total}' https://virida-frontend-3d.cleverapps.io/)
      - echo "Production response time: ${response_time}s"
      - if [ $(echo "$response_time > 2.0" | bc -l) -eq 1 ]; then echo "⚠️ Warning: High response time in production"; fi
    when:
      event: push
      branch: main

# ========================================
# ÉTAPE 7: NOTIFICATIONS ET RAPPORTS
# ========================================
  - name: 📊 Generate Report
    image: alpine:latest
    commands:
      - apk add --no-cache curl jq
      - echo "📊 Generating deployment report..."
      
      # Collecter les métriques
      - echo "## 🚀 VIRIDA Deployment Report" > deployment-report.md
      - echo "**Date:** $(date)" >> deployment-report.md
      - echo "**Branch:** $DRONE_BRANCH" >> deployment-report.md
      - echo "**Commit:** $DRONE_COMMIT_SHA" >> deployment-report.md
      - echo "**Author:** $DRONE_COMMIT_AUTHOR" >> deployment-report.md
      - echo "" >> deployment-report.md
      
      # Ajouter les URLs des services
      - echo "### 🌐 Deployed Services" >> deployment-report.md
      - echo "- Frontend 3D: https://virida-frontend-3d.cleverapps.io" >> deployment-report.md
      - echo "- AI/ML: https://virida-ai-ml.cleverapps.io" >> deployment-report.md
      - echo "- Gitea Database: Available on Clever Cloud (environment not working)" >> deployment-report.md
      
      # Sauvegarder le rapport
      - cat deployment-report.md
    when:
      event: [push, tag]
      branch: [main, staging]

  - name: 📢 Notify Success
    image: alpine:latest
    commands:
      - apk add --no-cache curl
      - echo "📢 Sending success notification..."
      - curl -X POST "$SLACK_WEBHOOK_URL" \
          -H "Content-Type: application/json" \
          -d '{
            "text": "✅ VIRIDA deployed successfully!",
            "attachments": [{
              "color": "good",
              "fields": [{
                "title": "Environment",
                "value": "'$DRONE_BRANCH'",
                "short": true
              }, {
                "title": "Commit",
                "value": "'$DRONE_COMMIT_SHA'",
                "short": true
              }]
            }]
          }'
    when:
      status: success
      event: [push, tag]

  - name: 📢 Notify Failure
    image: alpine:latest
    commands:
      - apk add --no-cache curl
      - echo "📢 Sending failure notification..."
      - curl -X POST "$SLACK_WEBHOOK_URL" \
          -H "Content-Type: application/json" \
          -d '{
            "text": "❌ VIRIDA deployment failed!",
            "attachments": [{
              "color": "danger",
              "fields": [{
                "title": "Environment",
                "value": "'$DRONE_BRANCH'",
                "short": true
              }, {
                "title": "Commit",
                "value": "'$DRONE_COMMIT_SHA'",
                "short": true
              }]
            }]
          }'
    when:
      status: failure
      event: [push, tag]

# ========================================
# CONFIGURATION DES SERVICES
# ========================================
services:
  - name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: virida_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - 5432

  - name: redis
    image: redis:7-alpine
    ports:
      - 6379

# ========================================
# CONFIGURATION DU CACHE
# ========================================
cache:
  - name: node_modules
    mount: /workspace/apps/frontend-3d/node_modules
  - name: python_cache
    mount: /root/.cache/pip
  - name: go_modules
    mount: /go/pkg/mod

# ========================================
# CONFIGURATION DES VOLUMES
# ========================================
volumes:
  - name: node_modules
    temp: {}
  - name: python_cache
    temp: {}
  - name: go_modules
    temp: {}
