---
kind: pipeline
type: docker
name: 🚀 VIRIDA Production Pipeline

platform:
  os: linux
  arch: amd64

environment:
  NODE_VERSION: "18"
  PYTHON_VERSION: "3.11"
  GO_VERSION: "1.21"
  ENVIRONMENT: "production"

trigger:
  branch: [main]
  event: [push, tag]

steps:
  - name: 📥 Checkout Code
    image: alpine/git:latest
    commands:
      - git clone $DRONE_GIT_HTTP_URL .
      - git checkout $DRONE_COMMIT_SHA

  - name: 🔒 Security Scan
    image: securecodewarrior/docker-security-scan:latest
    commands:
      - echo "🔒 Running comprehensive security scan..."
      - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock
        -v $(pwd):/workspace
        securecodewarrior/docker-security-scan:latest
        /workspace
    when:
      event: [push, tag]

  - name: 🧪 Full Test Suite
    image: node:18-alpine
    commands:
      - echo "🧪 Running full test suite for production..."
      - cd apps/frontend-3d && npm ci --cache .npm
      - cd apps/frontend-3d && npm run test:ci
      - cd apps/frontend-3d && npm run test:e2e
      - cd ../ai-ml && pip install -r requirements.txt
      - cd ../ai-ml && python -m pytest tests/ -v --cov=app --cov-report=xml
      # Note: Gitea/Drone tests disabled - Gitea environment not working

  - name: 🏗️ Production Build
    image: node:18-alpine
    commands:
      - echo "🏗️ Building applications for production..."
      - cd apps/frontend-3d && npm run build:production
      - cd ../ai-ml && python -m pip install --upgrade pip
      - cd ../ai-ml && pip install gunicorn
      # Note: Gitea/Drone build disabled - Gitea environment not working

  - name: 🐳 Docker Build
    image: docker:latest
    commands:
      - echo "🐳 Building Docker images..."
      - docker build -t virida-frontend-3d:latest -f apps/frontend-3d/Dockerfile apps/frontend-3d/
      - docker build -t virida-ai-ml:latest -f apps/ai-ml/Dockerfile apps/ai-ml/
      # Note: Gitea/Drone Docker build disabled - Gitea environment not working
      
      # Tag pour le registry
      - docker tag virida-frontend-3d:latest $DOCKER_REGISTRY/virida-frontend-3d:$DRONE_COMMIT_SHA
      - docker tag virida-ai-ml:latest $DOCKER_REGISTRY/virida-ai-ml:$DRONE_COMMIT_SHA
    when:
      event: [push, tag]

  - name: 🚀 Deploy to Production
    image: alpine:latest
    commands:
      - apk add --no-cache curl
      - echo "🚀 Deploying to production environment..."
      
      # Déployer Frontend 3D
      - cd apps/frontend-3d
      - tar -czf frontend-3d-production.tar.gz dist/
      - curl -X POST "$CLEVER_DEPLOY_URL/frontend-3d" \
          -H "Authorization: Bearer $CLEVER_TOKEN" \
          -F "archive=@frontend-3d-production.tar.gz"
      
      # Déployer AI/ML
      - cd ../ai-ml
      - tar -czf ai-ml-production.tar.gz app/ requirements.txt wsgi.py
      - curl -X POST "$CLEVER_DEPLOY_URL/ai-ml" \
          -H "Authorization: Bearer $CLEVER_TOKEN" \
          -F "archive=@ai-ml-production.tar.gz"
      
      # Note: Gitea/Drone deployment disabled - Gitea environment not working
      # Only Gitea database is available on Clever Cloud

  - name: 🧪 Production Health Checks
    image: curlimages/curl:latest
    commands:
      - echo "🧪 Running production health checks..."
      - sleep 90
      
      # Tests de santé critiques
      - curl -f https://virida-frontend-3d.cleverapps.io/health || exit 1
      - curl -f https://virida-ai-ml.cleverapps.io/health || exit 1
      # Note: Gitea/Drone health check disabled - Gitea environment not working
      
      # Tests fonctionnels avancés
      - curl -f https://virida-frontend-3d.cleverapps.io/api/status || exit 1
      - curl -f https://virida-ai-ml.cleverapps.io/api/health || exit 1
      # Note: Gitea/Drone API test disabled - Gitea environment not working
      
      echo "✅ All production health checks passed!"

  - name: 📊 Performance & Load Tests
    image: curlimages/curl:latest
    commands:
      - echo "📊 Running performance and load tests..."
      
      # Test de charge
      - for i in {1..20}; do
          response_time=$(curl -o /dev/null -s -w '%{time_total}' https://virida-frontend-3d.cleverapps.io/)
          echo "Request $i: ${response_time}s"
          if [ $(echo "$response_time > 2.0" | bc -l) -eq 1 ]; then
            echo "⚠️ Warning: High response time detected in production"
          fi
        done
      
      # Test de disponibilité
      - for i in {1..5}; do
          curl -f https://virida-frontend-3d.cleverapps.io/ || exit 1
          curl -f https://virida-ai-ml.cleverapps.io/ || exit 1
          # Note: Gitea/Drone availability test disabled - Gitea environment not working
          sleep 10
        done

  - name: 🔄 Blue-Green Deployment
    image: alpine:latest
    commands:
      - apk add --no-cache curl
      - echo "🔄 Performing blue-green deployment..."
      
      # Vérifier que l'ancienne version fonctionne
      - curl -f https://virida-frontend-3d.cleverapps.io/health || exit 1
      
      # Basculer le trafic vers la nouvelle version
      - curl -X POST "$CLEVER_SWITCH_URL/frontend-3d" \
          -H "Authorization: Bearer $CLEVER_TOKEN" \
          -d '{"version": "'$DRONE_COMMIT_SHA'"}'
      
      # Attendre la propagation
      - sleep 30
      
      # Vérifier que la nouvelle version fonctionne
      - curl -f https://virida-frontend-3d.cleverapps.io/health || exit 1
      
      echo "✅ Blue-green deployment completed successfully!"

  - name: 📊 Monitoring Setup
    image: alpine:latest
    commands:
      - apk add --no-cache curl
      - echo "📊 Setting up monitoring..."
      
      # Configurer les alertes
      - curl -X POST "$MONITORING_URL/alerts" \
          -H "Authorization: Bearer $MONITORING_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "service": "virida-frontend-3d",
            "url": "https://virida-frontend-3d.cleverapps.io/health",
            "threshold": 2.0,
            "enabled": true
          }'
      
      - curl -X POST "$MONITORING_URL/alerts" \
          -H "Authorization: Bearer $MONITORING_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "service": "virida-ai-ml",
            "url": "https://virida-ai-ml.cleverapps.io/health",
            "threshold": 2.0,
            "enabled": true
          }'

  - name: 📢 Production Notification
    image: alpine:latest
    commands:
      - apk add --no-cache curl
      - curl -X POST "$SLACK_WEBHOOK_URL" \
          -H "Content-Type: application/json" \
          -d '{
            "text": "🚀 VIRIDA production deployment completed successfully!",
            "attachments": [{
              "color": "good",
              "fields": [{
                "title": "Environment",
                "value": "Production",
                "short": true
              }, {
                "title": "Version",
                "value": "'$DRONE_COMMIT_SHA'",
                "short": true
              }, {
                "title": "URLs",
                "value": "Frontend: https://virida-frontend-3d.cleverapps.io\nAI/ML: https://virida-ai-ml.cleverapps.io\nGitea DB: Available on Clever Cloud",
                "short": false
              }, {
                "title": "Deployment Time",
                "value": "'$(date)'",
                "short": false
              }]
            }]
          }'

  - name: 📈 Rollback on Failure
    image: alpine:latest
    commands:
      - apk add --no-cache curl
      - echo "📈 Rolling back to previous version..."
      
      # Rollback Frontend
      - curl -X POST "$CLEVER_ROLLBACK_URL/frontend-3d" \
          -H "Authorization: Bearer $CLEVER_TOKEN"
      
      # Rollback AI/ML
      - curl -X POST "$CLEVER_ROLLBACK_URL/ai-ml" \
          -H "Authorization: Bearer $CLEVER_TOKEN"
      
      # Note: Gitea/Drone rollback disabled - Gitea environment not working
      
      echo "✅ Rollback completed"
    when:
      status: failure

services:
  - name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: virida_production
      POSTGRES_USER: production
      POSTGRES_PASSWORD: production
    ports:
      - 5432

  - name: redis
    image: redis:7-alpine
    ports:
      - 6379

cache:
  - name: node_modules
    mount: /workspace/apps/frontend-3d/node_modules
  - name: python_cache
    mount: /root/.cache/pip
  - name: go_modules
    mount: /go/pkg/mod

volumes:
  - name: node_modules
    temp: {}
  - name: python_cache
    temp: {}
  - name: go_modules
    temp: {}
