name: VIRIDA CI/CD Pipeline

on:
  push:
    branches: [ devops_crk ]
  pull_request:
    branches: [ devops_crk ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Validate YAML files
        run: |
          echo "Validating YAML configuration files..."
          find .gitea/workflows -name "*.yml" -type f 2>/dev/null | while read file; do
            echo "Validating $file"
            if [ -f "$file" ]; then
              head -1 "$file" | grep -q "name:" || { echo "❌ Invalid workflow: $file"; exit 1; }
            fi
          done
          echo "✅ All workflow YAML files are valid"
          
      - name: Validate Dockerfiles
        run: |
          echo "Validating Dockerfiles..."
          if command -v docker &> /dev/null && docker ps &> /dev/null; then
            find . -maxdepth 1 -name "Dockerfile*" -type f | while read file; do
              echo "Validating $file"
              docker run --rm -v "$(pwd):/workspace" hadolint/hadolint hadolint "/workspace/$file" || echo "⚠️ Warning: $file validation had issues"
            done
          else
            echo "⚠️ Docker not available, skipping Dockerfile validation"
          fi

  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Test CI/CD Scripts
        run: |
          echo "Testing CI/CD scripts..."
          chmod +x scripts/*.sh
          ./scripts/test-pipeline-gitea.sh

  build:
    runs-on: ubuntu-latest
    name: Build CI/CD Infrastructure
    needs: [validate, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Gitea Runner Docker Image
        run: |
          echo "Building Gitea Runner Docker image..."
          docker build -f Dockerfile.gitea-runner -t virida-gitea-runner .
          echo "Gitea Runner build completed"

  security:
    runs-on: ubuntu-latest
    name: Security Scan
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          
      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  sonarqube:
    runs-on: ubuntu-latest
    name: SonarQube Analysis
    needs: [security]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  deploy-staging:
    runs-on: ubuntu-latest
    name: Deploy CI/CD to Staging
    needs: [sonarqube]
    if: github.ref == 'refs/heads/devops_crk'
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Clever Tools
        run: |
          echo "Installing Clever Cloud CLI..."
          curl -fsSL https://clever-tools.clever-cloud.com/releases/2.7.0/clever-tools-linux.tar.gz | tar -xz
          sudo mv clever /usr/local/bin/
          clever --version
          
      - name: Configure Clever Cloud
        run: |
          echo "Configuring Clever Cloud credentials..."
          clever login --token ${{ secrets.CLEVER_TOKEN }} --secret ${{ secrets.CLEVER_SECRET }}
          
      - name: Deploy Gitea Runner to Staging
        run: |
          echo "Deploying Gitea Runner to staging..."
          clever link --alias virida-gitea-runner-staging
          clever deploy
          
      - name: Health Check Staging
        run: |
          echo "Performing health checks..."
          sleep 30  # Attendre le déploiement
          echo "CI/CD infrastructure deployed to staging"

  deploy-production:
    runs-on: ubuntu-latest
    name: Deploy CI/CD to Production
    needs: [sonarqube]
    if: github.ref == 'refs/heads/devops_crk'
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Clever Tools
        run: |
          echo "Installing Clever Cloud CLI..."
          curl -fsSL https://clever-tools.clever-cloud.com/releases/2.7.0/clever-tools-linux.tar.gz | tar -xz
          sudo mv clever /usr/local/bin/
          clever --version
          
      - name: Configure Clever Cloud
        run: |
          echo "Configuring Clever Cloud credentials..."
          clever login --token ${{ secrets.CLEVER_TOKEN }} --secret ${{ secrets.CLEVER_SECRET }}
          
      - name: Deploy Gitea Runner to Production
        run: |
          echo "Deploying Gitea Runner to production..."
          clever link --alias virida-gitea-runner
          clever deploy
          
      - name: Health Check Production
        run: |
          echo "Performing production health checks..."
          sleep 30  # Attendre le déploiement
          echo "CI/CD infrastructure deployed to production"

  notify:
    runs-on: ubuntu-latest
    name: Notify Results
    needs: [deploy-staging, deploy-production]
    if: always()
    steps:
      - name: Notify Success
        if: needs.deploy-staging.result == 'success' || needs.deploy-production.result == 'success'
        run: |
          echo "CI/CD Deployment successful! 🎉"
          # Ici vous pouvez ajouter des notifications Slack, email, etc.
          
      - name: Notify Failure
        if: needs.deploy-staging.result == 'failure' || needs.deploy-production.result == 'failure'
        run: |
          echo "CI/CD Deployment failed! ❌"
          # Notification d'échec