name: Deploy VIRIDA Native Applications

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy-virida-app:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      NODE_VERSION: '18'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: virida_app/package-lock.json

      - name: Install dependencies (virida_app)
        working-directory: virida_app
        run: npm ci

      - name: Lint frontend (virida_app)
        working-directory: virida_app
        run: npm run lint

      - name: Build frontend (virida_app)
        working-directory: virida_app
        run: npm run build

      - name: Install Clever Tools
        run: npm install -g clever-tools

      - name: Deploy virida_app to Clever Cloud
        working-directory: virida_app
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
        run: clever deploy --alias virida-frontend-app

  deploy-frontend-3d:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy Frontend 3D
        run: |
          cd apps/frontend-3d
          clever deploy --alias virida-frontend-3d
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}

  deploy-backend-api:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: virida_api/package-lock.json

      - name: Install dependencies (virida_api)
        working-directory: virida_api
        run: npm ci

      - name: Lint backend (virida_api)
        working-directory: virida_api
        run: npm run lint

      - name: Run backend tests (virida_api)
        working-directory: virida_api
        run: npm run test -- --runInBand

      - name: Install Clever Tools
        run: npm install -g clever-tools

      - name: Deploy Backend API
        working-directory: virida_api
        run: clever deploy --alias virida-backend-api
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}

  deploy-ai-ml:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy AI/ML
        run: |
          cd apps/ai-ml
          clever deploy --alias virida-ai-ml
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}

  deploy-monitoring:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy Prometheus
        run: |
          cd apps/prometheus
          clever deploy --alias virida-prometheus
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
      
      - name: Deploy Grafana
        run: |
          cd apps/grafana
          clever deploy --alias virida-grafana
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}

  health-check:
    runs-on: ubuntu-latest
    needs: [build-and-deploy-virida-app, deploy-frontend-3d, deploy-backend-api, deploy-ai-ml, deploy-monitoring]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Health Check Frontend
        run: |
          sleep 30
          curl -f https://virida-frontend-3d.cleverapps.io/health || exit 1
      
      - name: Health Check virida_app
        run: |
          curl -f https://virida-frontend-app.cleverapps.io/health || exit 1
      
      - name: Health Check Backend
        run: |
          curl -f https://virida-backend-api.cleverapps.io/health || exit 1
      
      - name: Health Check AI/ML
        run: |
          curl -f https://virida-ai-ml.cleverapps.io/health || exit 1


